name: CI for Backend API

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
    types: [opened, synchronize, reopened]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v3

      - name:  caching Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.14
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: lint the api
        run: npm run lint

      - name:  Build application
        run: npm run build

      - name: Run e2e tests
        run: npm run test:e2e
